eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
management:
  endpoints:
    refresh:
      enabled: true
    web:
      exposure:
        include: refresh

  tracing:
    sampling:
      probability: 1
